Myfinance-web-dotnet/Models/ErrorViewModel.cs
namespace Myfinance_web_dotnet.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Myfinance-web-dotnet/Models/PlanoContaModel.cs
using System.ComponentModel.DataAnnotations;

namespace Myfinance_web_dotnet.Models{

    public class PlanoContaModel
    {
        public int? Id{get;set;}

        [Required (ErrorMessage ="Informe a descrição do item de Plano de Conta!")]
        public string? Descricao{get; set;}

        [Required (ErrorMessage ="Informe a tipo do item de Plano de Conta!")]
        public string? Tipo{get; set; }
        
    }
}

Myfinance-web-dotnet/Models/TransacaoModel.cs
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Myfinance_web_dotnet.Models{

    public class TransacaoModel
    {
        public int? Id {get;set; }
        public string? Historico { get; set; }
        public DateTime Data { get; set; }
        
         [Required (ErrorMessage ="Informe o valor da Transação!")]
         [Range(0.01, 99999999999.99, ErrorMessage ="O valor deve ser menor que 0")]
        public decimal Valor { get; set; }
        public decimal PlanoContaId { get; set; }
        public PlanoContaModel? ItemPlanoConta { get; set; }

        public IEnumerable<SelectListItem>? PlanoContas { get; set; }


        
    }
}

Myfinance-web-dotnet/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Myfinance_web_dotnet.Models;

namespace Myfinance_web_dotnet.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Myfinance-web-dotnet/Controllers/TransacaoController.cs
using Microsoft.AspNetCore.Mvc;
using MyFinance_web_dotnet.Infrastruture;
using Myfinance_web_dotnet.Models;
using AutoMapper;
using Myfinance_web_dotnet.Services;
using Microsoft.AspNetCore.Mvc.Rendering;

[Route("[controller]")]
public class TransacaoController : Controller
{
    private readonly IMapper _mapper;
    private readonly MyFinanceDbContext _myFinanceDbContext;

    private readonly ILogger<TransacaoController> _logger;
    private readonly ITransacaoService _transacaoService;
    private readonly IPlanoContaService _planoContaService;
    

    public TransacaoController(
        ILogger<TransacaoController> logger,
        ITransacaoService transacaoService,        
        IPlanoContaService planoContaService,
        MyFinanceDbContext myFinanceDbContext,
        IMapper mapper)
    {
        _logger = logger;
        _myFinanceDbContext = myFinanceDbContext;
        _mapper = mapper;
        _transacaoService = transacaoService;
        _planoContaService = planoContaService;
    }

    public IActionResult Index()
    {        
        var lista = _transacaoService.ListarRegistros();   
        ViewBag.ListaTransacao = lista;
        return View();
    }

    [HttpPost]
    [Route("Cadastro")]
    [Route("Cadastro/{id}")]
    public IActionResult Cadastro(TransacaoModel model, int? id)
    {          
        if(ModelState.IsValid) 
        {              
            _transacaoService.Salvar(model);
            return RedirectToAction("Cadastro");
        }    
        else 
        {
             var listaPlanoConta = _planoContaService.ListarRegistros();
            var selectListPlanoContas = new SelectList(listaPlanoConta,"Id","Descricao");
            model.PlanoContas = selectListPlanoContas;
            return View(model); 
        }
         
    }   


    [HttpGet]
    [Route("Cadastro")]
    [Route("Cadastro/{id}")]
    public IActionResult Cadastro(int? id)
    {  
        var listaPlanoConta = _planoContaService.ListarRegistros();
        var selectListPlanoContas = new SelectList(listaPlanoConta,"Id","Descricao");

        if(id != null ){
           var model = _transacaoService.RetornarRegistro((int)id);
            model.PlanoContas = selectListPlanoContas;
           return View(model);
        }       
        else{ 
           var model =  new TransacaoModel();
            model.PlanoContas = selectListPlanoContas;
           return View(model);
        }       
    } 




    [HttpGet]
    [Route("Excluir/{id}")]
    public IActionResult Excluir(int id)
    {        
       _transacaoService.Excluir(id);
       return RedirectToAction("Index");
    }
}

Myfinance-web-dotnet/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Myfinance-web-dotnet/Views/PlanoConta/Cadastro.cshtml
@model PlanoContaModel

@{
    ViewData["Title"] = (Model.Id > 0) ? "Editar Plano de Contas" : "Cadastro de Plano de Contas";
}

<h1>@ViewData["Title"]</h1>
<form asp-controller="PlanoConta" asp-action="Salvar" method="post">
    @Html.AntiForgeryToken()
    <div class="container">
        <div class="mb-3">
            <label class="form-label">Descrição</label>
            <input type="hidden" id="txtId" class="form-control" asp-for="Id" />
            <input type="text" id="txtNome" class="form-control" asp-for="Descricao" />
            <span asp-validation-for="Descricao" class="text-danger"></span>
        </div>
        <div class="mb-3">
            <label>@Html.RadioButtonFor(m => m.Tipo, "D") Despesa</label>
            <label>@Html.RadioButtonFor(m => m.Tipo, "R") Receita</label>
        </div>
        <div class="mb-3">
            <button type="submit" class="btn btn-primary btn-lg">Salvar</button>
            <button type="button" class="btn btn-secondary btn-lg" onclick="Voltar()">Cancelar</button>
        </div>
    </div>
</form>
<script>
    function Voltar() {
        window.location.href = "/PlanoConta";
    }
</script>

Myfinance-web-dotnet/Views/PlanoConta/Index.cshtml
@{
    ViewData["Title"] = "Plano Contas";
}

<button type="button" class="btn btn_block btn-primary" onclick="Novo()">Criar item de Plano de Conta</button>
<br><br>

<table class="table table-bordered">
    <tr>
        <th>Id</th>
        <th>Descrição</th>
        <th>Tipo</th>
        <th>#</th>
        <th>#</th>
    </tr>


    @{
    foreach (var item in (List<PlanoContaModel>)ViewBag.ListaPlanoConta)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.Descricao</td>
                <td>@item.Tipo</td>
                <td><button Type="button" class="btn btn-block btn-outline-warning" onclick="Atualizar(@item.Id.ToString())">Editar</button></td>
                
                <td><button Type="button" class="btn btn-block btn-outline-danger" onclick="Excluir(@item.Id.ToString())">Excluir</button></td>
            </tr>
        }
    }
</table>

<script>
    function Novo()
    {
        window.location.href = "..PlanoConta/Cadastro";
    }
    function Atualizar()
    {
        window.location.href = "..PlanoConta/Cadastro"+ Id;
    }
</script>

Myfinance-web-dotnet/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Myfinance_web_dotnet</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Myfinance_web_dotnet.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Myfinance_web_dotnet</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PlanoConta" asp-action="Index">Plano Conta</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Transacao" asp-action="Index">Transações Financeiras</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Myfinance_web_dotnet - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script> 
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Myfinance-web-dotnet/Views/Transacao/Cadastro.cshtml
@model TransacaoModel

@{
    ViewData["Title"] = "Registro de Transação Financeira";
}

<h1>@ViewData["Title"]</h1>

<form asp-controller="Transacao" asp-action="Cadastro" method="post">
    <div class="container">

        <div class="mb-3">
            <label class="form-label">Data</label>
            <input type="hidden" id="txtId" class="form-control" asp-for="Id" /> 
            <input type="date" id="txtData" class="form-control" asp-for="Data" />
        </div>

        <div class="mb-3">
            <label class="form-label">Valor</label>
            <input type="text" id="txtValor" class="form-control" asp-for="Valor" step="0.01" />
            <span asp-validation-for="Valor" class="text-damger"></span>
        </div>

        <div class="mb-3">
            <label class="form-label">Item Plano Conta</label>
            @Html.DropDownListFor(m => m.PlanoContaId, Model.PlanoContas, new { @class = "form-select" })
        </div>

        <div class="mb-3">
            <label class="form-label">Histórico</label>
            <input type="text" id="txtNome" class="form-control" asp-for="Historico" />
        </div>

        <div class="mb-3">
            <button type="submit" class="btn btn-primary btn-lg">Salvar</button>
            <button type="button" class="btn btn-secondary btn-lg" onclick="Voltar()">Cancelar</button>
        </div>
    </div>
</form>

<script>
    function Voltar() {
        window.location.href = "/Transacao"
    }
</script>

Myfinance-web-dotnet/Views/Transacao/Index.cshtml
@{
    ViewData["Title"] = "Transação";
}

<button type="button" class="btn btn_block btn-primary" onclick="Novo()">Registrar transação financeira </button>
<br><br>

<table class="table table-bordered">
    <tr>
        <th>Id</th>
        <th>Historico</th>
        <th>Tipo</th>
        <th>Data</th>
        <th>Valor</th>
        <th>#</th>
        <th>#</th>
    </tr>


    @{
    foreach (var item in (List<TransacaoModel>)ViewBag.ListaTransacao)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.Historico</td>
                <td>@item.ItemPlanoConta.Tipo</td>
                <td>@item.Data</td>
                <td>@item.Valor</td>
                <td><button Type="button" class="btn btn-block btn-outline-warning" onclick="Editar(@item.Id.ToString())">Editar</button></td>
                
                <td><button Type="button" class="btn btn-block btn-outline-danger" onclick="Excluir(@item.Id.ToString())">Excluir</button></td>
            </tr>
        }
    }
</table>

<script>
    function Novo()
    {
        window.location.href = "../Transacao/Cadastro";
    }
    function Editar(id)
    {
        window.location.href = "../Transacao/Cadastro/"+ id;
    }
    function Excluir(id)
    {
        window.location.href = "../Transacao/Excluir/"+ id;
    }
</script>